name: Deploy to GH Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: nextjs-blog

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build 
        run: 
          npm install
          npm run build 
          npm run export

      # - name: Add .nojekyll
      #   run: |
      #     touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'  